### ISSUE TITLE
Extension seems to break utopian guidelines webpage

### ISSUE THREAD

**Issue by quetzalcoatl** [Jestemkioskiem/utopian.rocks.ext#3]
I'm pretty sure there's some small bug in the extension. When I have this extension turned ON, then the Guidelines page from utopian-io gets some damage and looks like this:

![one](https://media.discordapp.net/attachments/510091682893791252/510092072837971978/unknown.png?width=327&height=376)

The part above red line was done with the extension installed but deactivated, and below red line is after activating the extension.

Aside from the obvious changes in the layoutu, the icons are still clickable but they no longer display any detailed content.

By the way, it'd be a good idea to add a link to this repo to the ChromeStore web page related to this plugin, it took me a while and a bit of luck to correlate this repo to https://chrome.google.com/webstore/detail/utopian/enodmgbbodkljcmenikaolnohjmlghcb (thanks again, Oups :) )

**Comment by quetzalcoatl** [comment]
There's something more odd than CSS clash. I just noticed that on a working page, the DOM tree is:
```
<div class="categories slick-initialized slick-slider slick-dotted">
  <button class="slick-prev slick-arrow slick-disabled" aria-label="Previous" type="button" aria-disabled="true" style="">Previous</button><div class="slick-list draggable">
    <div class="slick-track" style="opacity: 1; width: 2405px; transform: translate3d(0px, 0px, 0px);">
      <div class="slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" role="tabpanel" id="slick-slide00" style="width: 185px;">
        <div>
          <div style="width: 100%; display: inline-block;">
            <a href="javascript:void(0)" id="suggestions" class="circle suggestions reverse" data-toggle="tooltip" data-placement="right" title="" style="transform: scale(1);" data-original-title="Suggestions" tabindex="0">
              <svg style=
```
and on a broken page it is just:
```
<div class="categories">
  <div>
    <a href="javascript:void(0)" id="suggestions" class="circle reverse suggestions" data-toggle="tooltip" data-placement="right" title="" style="transform: scale(1);" data-original-title="Suggestions">
      <svg style=....
```
Compare the topmost categories tag and innermost div/div/ahref/svg - they are mostly the same except for the injections from, I guess, a 'slick' component.
It seems that the 'slick' was not initialized on the 'container' properly, at least the classes on `container` indicate that.

That led me to the console-log (I feel so lame, I should have checked it first) and to this error in the log:
```
Uncaught TypeError: $(...).slick is not a function
    at generateSlick ((index):306)
    at HTMLSpanElement.<anonymous> ((index):290)
```
Place pointed out by the line numbers is in the Guidelines' HTML itself:
```
    function generateSlick() {
      $('.categories').slick({       // <---- error HERE
        dots: true,
        infinite: false,
        speed: 300,
        slidesToShow: 6,
        slidesToScroll: 3,
        responsive: [{
            breakpoint: 1024,
            settings: {
              slidesToShow: 4,
              slidesToScroll: 2,
              infinite: true,
              dots: true
            }
          },
          .......
        ]
      });
    }
```
and this pretty much proves that the `$` is damaged. It should contain the `slick` plugin, but it does not.

Back then I've noticed that the extension comes with its own jQuery, so currently my best guess is that your jQuery leaks onto the processed webpage and shadows the original one, and obviously your one is 'clean' without any plugins like slick:
![image](https://user-images.githubusercontent.com/1564880/48470626-37426480-e7f2-11e8-85a1-c316185f2928.png)

**Comment by Jestemkioskiem** [comment]
Woah! I haven't had the time to properly look into this so thank you for the very detailed report, this is incredible work!

I think I know why it leaks into Utopian and there's probably an easy fix to this issue which I'll be looking into asap. Thank you!

**Comment by Jestemkioskiem** [comment]
This has now been fixed with a temporary solution as of 929a415 (1.1.2). I would prefer to not inject jquery at all but right now there's no way I've got time to rewrite the code to native js. This will work for as long as steemit doesn't inject their own jquery. 

Pushing the new version to the chrome store. Thanks again!

**Comment by quetzalcoatl** [comment]
Great! I'll update&recheck as soon as it's visible in store :)

**Comment by quetzalcoatl** [comment]
Strange, the Store still shows v1.1.1 from 8.Oct as the current one. Have you really pushed the update?

**Comment by Jestemkioskiem** [comment]
I am positive I did push the update, but I'll try again. Thanks for letting me know.

**Comment by quetzalcoatl** [comment]
Alright, now it's 1.1.2 and the fix works, the guidelines page looks fine. Thanks!
